version: "3"
networks:
  my_network:
services:
  node1:
    image: cassandra:latest
    container_name: node1
    hostname: node1
    mem_limit: 2g
    networks:
      - my_network
    ports:
      - "9042:9042"
    environment: &environment
      CASSANDRA_SEEDS: "node1,node2"
      CASSANDRA_CLUSTER_NAME: mbaperro
      CASSANDRA_USER: user
      CASSANDRA_PASSWORD: password
    volumes:
      - ./scripts/bash:/docker_entrypoint.sh
      - ./scripts/cql/node1:/tmp/cql
    command: bash ./docker_entrypoint.sh/execute-cql.sh
    expose: &expose
      - 7000
      - 7001
      - 7199
      - 9042
      - 9142
  node2:
    image: cassandra:latest
    container_name: node2
    hostname: node2
    mem_limit: 2g
    networks:
      - my_network
    ports:
      - "9043:9042"
    environment: *environment
    volumes:
      - ./scripts/bash:/docker_entrypoint.sh
      - ./scripts/cql/node2:/tmp/cql
    command: bash ./docker_entrypoint.sh/execute-cql.sh
    expose: *expose
  node3:
    image: cassandra:latest
    container_name: node3
    hostname: node3
    mem_limit: 2g
    networks:
      - my_network
    ports:
      - "9044:9042"
    environment: *environment
    volumes:
      - ./scripts/bash:/docker_entrypoint.sh
      - ./scripts/cql/node3:/tmp/cql
    command: bash ./docker_entrypoint.sh/execute-cql.sh
    expose: *expose
